name: Add Security Headers

on:
  workflow_dispatch: # Ручной запуск
  push:
    paths:
      - '*.html' # Запуск при изменении HTML файлов

jobs:
  add-security-headers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Add Security Headers to HTML files
      run: |
        echo "🔒 Добавляем Security Headers в HTML файлы..."
        
        # Определяем Security Headers для вставки
        SECURITY_HEADERS='    <!-- Security Headers -->
        <meta http-equiv="Content-Security-Policy" content="default-src '\''self'\''; script-src '\''self'\'' '\''unsafe-inline'\'' https://www.googletagmanager.com https://www.google-analytics.com https://googleads.g.doubleclick.net; style-src '\''self'\'' '\''unsafe-inline'\'' https://fonts.googleapis.com; font-src '\''self'\'' https://fonts.gstatic.com; img-src '\''self'\'' data: https://www.google-analytics.com https://www.googletagmanager.com; connect-src '\''self'\'' https://www.google-analytics.com https://analytics.google.com https://www.digistore24.com; frame-src https://www.google.com;">
        <meta http-equiv="X-Frame-Options" content="DENY">
        <meta http-equiv="X-Content-Type-Options" content="nosniff">
        <meta http-equiv="Referrer-Policy" content="strict-origin-when-cross-origin">
        <meta http-equiv="Permissions-Policy" content="geolocation=(), microphone=(), camera=()">
        <meta http-equiv="X-XSS-Protection" content="1; mode=block">'
        
        # Счетчик обработанных файлов
        PROCESSED=0
        
        # Обрабатываем все HTML файлы
        for file in *.html; do
          if [ -f "$file" ]; then
            echo "📄 Обрабатываем: $file"
            
            # Проверяем, есть ли уже Security Headers
            if grep -q "Security Headers" "$file"; then
              echo "   ⚠️  Security Headers уже есть, пропускаем"
            else
              # Находим закрывающий тег </head> и вставляем перед ним
              if grep -q "</head>" "$file"; then
                # Создаем временный файл с добавленными headers
                sed "s|</head>|$SECURITY_HEADERS\n</head>|" "$file" > "${file}.tmp"
                mv "${file}.tmp" "$file"
                echo "   ✅ Security Headers добавлены"
                PROCESSED=$((PROCESSED + 1))
              else
                echo "   ❌ Не найден тег </head>"
              fi
            fi
          fi
        done
        
        echo ""
        echo "📊 Обработано файлов: $PROCESSED"
        echo "🔒 Security Headers добавлены!"
    
    - name: Verify Security Headers
      run: |
        echo "🔍 Проверяем добавленные Security Headers..."
        echo ""
        
        for file in *.html; do
          if [ -f "$file" ]; then
            echo "📄 $file:"
            
            # Проверяем каждый header
            if grep -q "Content-Security-Policy" "$file"; then
              echo "   ✅ Content-Security-Policy"
            else
              echo "   ❌ Content-Security-Policy НЕ НАЙДЕН"
            fi
            
            if grep -q "X-Frame-Options" "$file"; then
              echo "   ✅ X-Frame-Options"
            else
              echo "   ❌ X-Frame-Options НЕ НАЙДЕН"
            fi
            
            if grep -q "X-Content-Type-Options" "$file"; then
              echo "   ✅ X-Content-Type-Options"
            else
              echo "   ❌ X-Content-Type-Options НЕ НАЙДЕН"
            fi
            
            if grep -q "Referrer-Policy" "$file"; then
              echo "   ✅ Referrer-Policy"
            else
              echo "   ❌ Referrer-Policy НЕ НАЙДЕН"
            fi
            
            echo ""
          fi
        done
    
    - name: Commit changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        
        if git diff --quiet; then
          echo "🔄 Нет изменений для коммита"
        else
          git add *.html
          git commit -m "🔒 Add Security Headers to HTML files

          - Content-Security-Policy с поддержкой GA4 и DigitalStore24
          - X-Frame-Options: DENY
          - X-Content-Type-Options: nosniff  
          - Referrer-Policy: strict-origin-when-cross-origin
          - Permissions-Policy: блокировка геолокации/микрофона/камеры
          - X-XSS-Protection: включена защита"
          
          git push
          echo "✅ Изменения закоммичены и отправлены!"
        fi
    
    - name: Summary
      run: |
        echo "🎉 Security Headers успешно добавлены!"
        echo ""
        echo "🔒 Добавленные заголовки:"
        echo "   • Content-Security-Policy (с поддержкой GA4/DigitalStore24)"
        echo "   • X-Frame-Options: DENY"  
        echo "   • X-Content-Type-Options: nosniff"
        echo "   • Referrer-Policy: strict-origin-when-cross-origin"
        echo "   • Permissions-Policy: geolocation/microphone/camera блокированы"
        echo "   • X-XSS-Protection: включена"
        echo ""
        echo "🧪 Следующий шаг: тест на securityheaders.com"
        echo "🌐 Проверьте: https://securityheaders.com/?q=danilichev.info"
