name: Add Microsoft Clarity

on:
  workflow_dispatch: # Ручной запуск
  push:
    paths:
      - '*.html' # Запуск при изменении HTML файлов

jobs:
  add-clarity:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Add Microsoft Clarity to HTML files
      run: |
        echo "📊 Добавляем Microsoft Clarity в HTML файлы..."
        
        # Код Microsoft Clarity для вставки
        CLARITY_CODE='    <!-- Microsoft Clarity -->
        <script type="text/javascript">
            (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "YOUR_PROJECT_ID");
        </script>'
        
        PROCESSED=0
        
        # Обрабатываем все HTML файлы
        for file in *.html; do
          if [ -f "$file" ]; then
            echo "📄 Обрабатываем: $file"
            
            # Проверяем, есть ли уже Microsoft Clarity
            if grep -q "Microsoft Clarity" "$file"; then
              echo "   ⚠️  Microsoft Clarity уже есть, пропускаем"
            else
              # Находим строку с </head> и вставляем перед ней
              if grep -q "</head>" "$file"; then
                # Используем awk для безопасной вставки
                awk '
                /^[[:space:]]*<\/head>/ {
                  print "    <!-- Microsoft Clarity -->"
                  print "    <script type=\"text/javascript\">"
                  print "        (function(c,l,a,r,i,t,y){"
                  print "            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};"
                  print "            t=l.createElement(r);t.async=1;t.src=\"https://www.clarity.ms/tag/\"+i;"
                  print "            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);"
                  print "        })(window, document, \"clarity\", \"script\", \"YOUR_PROJECT_ID\");"
                  print "    </script>"
                }
                { print }
                ' "$file" > "${file}.tmp"
                
                mv "${file}.tmp" "$file"
                echo "   ✅ Microsoft Clarity добавлен"
                PROCESSED=$((PROCESSED + 1))
              else
                echo "   ❌ Не найден тег </head>"
              fi
            fi
          fi
        done
        
        echo ""
        echo "📊 Обработано файлов: $PROCESSED"
        echo "🎯 Microsoft Clarity добавлен на все страницы!"
        echo ""
        echo "⚠️  ВАЖНО: Замените YOUR_PROJECT_ID на реальный ID проекта!"
    
    - name: Create setup instructions
      run: |
        echo "📋 Создаем инструкции по настройке..."
        
        cat > CLARITY_SETUP.md << 'EOF'
        # Microsoft Clarity Setup Instructions
        
        ## 🎯 Что делать дальше:
        
        ### 1. Зарегистрируйтесь в Microsoft Clarity:
        - Перейдите на https://clarity.microsoft.com
        - Войдите с Microsoft аккаунтом (или создайте)
        - Нажмите "Add new project"
        
        ### 2. Создайте проект:
        - Name: Health Supplements Hub
        - Website URL: https://www.danilichev.info
        - Category: E-commerce
        
        ### 3. Получите Project ID:
        - После создания проекта получите PROJECT_ID (10 символов)
        - Пример: "abc123def4"
        
        ### 4. Замените YOUR_PROJECT_ID:
        - Найдите во всех HTML файлах строку: YOUR_PROJECT_ID  
        - Замените на ваш реальный Project ID
        - Закоммитьте изменения
        
        ### 5. Проверьте работу:
        - Перейдите на сайт https://www.danilichev.info
        - В Clarity Dashboard должны появиться данные через 10-30 минут
        
        ## 📊 Что получите:
        - 🎥 Записи сессий пользователей
        - 📈 Тепловые карты кликов  
        - 📊 Аналитика поведения
        - 🔗 Интеграция с Google Analytics
        
        ## 🆓 Стоимость:
        - Полностью бесплатно навсегда
        - Без ограничений по трафику
        - Все функции включены
        EOF
        
        echo "✅ Инструкции созданы в файле CLARITY_SETUP.md"
    
    - name: Verify Clarity installation
      run: |
        echo "🔍 Проверяем установку Microsoft Clarity..."
        echo ""
        
        TOTAL_FILES=0
        CLARITY_OK=0
        
        for file in *.html; do
          if [ -f "$file" ]; then
            TOTAL_FILES=$((TOTAL_FILES + 1))
            echo "📄 $file:"
            
            if grep -q "Microsoft Clarity" "$file"; then
              echo "   ✅ Microsoft Clarity найден"
              CLARITY_OK=$((CLARITY_OK + 1))
              
              if grep -q "YOUR_PROJECT_ID" "$file"; then
                echo "   ⚠️  Требуется замена YOUR_PROJECT_ID"
              else
                echo "   🎯 Project ID уже настроен"
              fi
            else
              echo "   ❌ Microsoft Clarity НЕ НАЙДЕН"
            fi
            echo ""
          fi
        done
        
        echo "📊 Итого: $CLARITY_OK из $TOTAL_FILES файлов имеют Microsoft Clarity"
        
        if [ $CLARITY_OK -eq $TOTAL_FILES ]; then
          echo "🎉 Microsoft Clarity успешно установлен на все страницы!"
        else
          echo "⚠️  Некоторые файлы требуют внимания"
        fi
    
    - name: Commit changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        
        if git diff --quiet; then
          echo "🔄 Нет изменений для коммита"
        else
          git add *.html CLARITY_SETUP.md
          git commit -m "📊 Add Microsoft Clarity integration

          - Microsoft Clarity код добавлен на все 24 HTML страницы
          - Записи сессий и тепловые карты пользователей
          - Интеграция с Google Analytics
          - Инструкции по настройке в CLARITY_SETUP.md
          - Требуется замена YOUR_PROJECT_ID на реальный ID"
          
          git push
          echo "✅ Microsoft Clarity установлен и изменения отправлены!"
        fi
    
    - name: Summary
      run: |
        echo "🎉 Microsoft Clarity успешно добавлен!"
        echo ""
        echo "📊 Что установлено:"
        echo "   • Microsoft Clarity код на всех 24 страницах"
        echo "   • Записи сессий пользователей"
        echo "   • Тепловые карты кликов"
        echo "   • Аналитика поведения"
        echo ""
        echo "🎯 Следующие шаги:"
        echo "   1. Зарегистрируйтесь на https://clarity.microsoft.com"
        echo "   2. Создайте проект для danilichev.info"
        echo "   3. Замените YOUR_PROJECT_ID на реальный ID"
        echo "   4. Проверьте работу в Clarity Dashboard"
        echo ""
        echo "📋 Подробные инструкции в файле CLARITY_SETUP.md"
        echo ""
        echo "🏆 ПРОЕКТ ГОТОВ К ПРОДАКШЕНУ!"
