name: Daily Backup

on:
  schedule:
    # Запуск каждый день в 12:00 UTC (15:00 МСК)
    - cron: '0 12 * * *'
  workflow_dispatch: # Возможность запуска вручную

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set backup date
      run: |
        echo "BACKUP_DATE=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV
    
    - name: Create backup archive
      run: |
        # Простой архив основных файлов
        tar -czf backup-${{ env.BACKUP_DATE }}.tar.gz *.html *.css *.js *.yml *.xml *.txt *.ico *.png 2>/dev/null || true
        ls -lh backup-${{ env.BACKUP_DATE }}.tar.gz
    
    - name: Create backup info
      run: |
        echo "# Health Supplements Hub Backup - ${{ env.BACKUP_DATE }}" > backup-info.md
        echo "Backup created: $(date)" >> backup-info.md
        echo "Repository: ${{ github.repository }}" >> backup-info.md
        echo "Commit: ${{ github.sha }}" >> backup-info.md
        echo "HTML pages: $(ls *.html 2>/dev/null | wc -l)" >> backup-info.md
        echo "Total files in backup: $(tar -tzf backup-${{ env.BACKUP_DATE }}.tar.gz | wc -l)" >> backup-info.md
    
    - name: Create Release with backup
      uses: softprops/action-gh-release@v1
      with:
        tag_name: backup-${{ env.BACKUP_DATE }}
        name: "📦 Daily Backup - ${{ env.BACKUP_DATE }}"
        body: |
          🔄 **Автоматический ежедневный бекап**
          
          📅 **Дата:** ${{ env.BACKUP_DATE }}
          🏷️ **Коммит:** ${{ github.sha }}
          
          📊 **Включено в архив:**
          - HTML страницы (24 шт)
          - CSS/JS файлы  
          - GitHub Actions (yml)
          - Конфигурация (xml, txt)
          - Иконки и изображения
          
          💾 **Скачать:** backup-${{ env.BACKUP_DATE }}.tar.gz
          
          ⏰ **Следующий бекап:** завтра в 12:00 UTC (15:00 МСК)
        files: |
          backup-${{ env.BACKUP_DATE }}.tar.gz
          backup-info.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Summary
      run: |
        echo "✅ Бекап успешно создан!"
        echo "📦 Архив: backup-${{ env.BACKUP_DATE }}.tar.gz"
        echo "🏷️ Релиз: backup-${{ env.BACKUP_DATE }}"
        echo "📊 Размер: $(ls -lh backup-${{ env.BACKUP_DATE }}.tar.gz | awk '{print $5}')"
        echo "⏰ Следующий бекап: завтра в 12:00 UTC"
